server.port=8081
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/chat?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=TRUE
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# Socket.IO Server Configuration
# This is where your WebSocket connections will be established
# Binds to all available network interfaces. Use 'localhost' if only accessible locally.
socket.io.host=0.0.0.0
# Dedicated port for Socket.IO server
socket.io.port=9092

# Logging (optional, for more verbose Socket.IO logging)
logging.level.com.corundumstudio.socketio=DEBUG
